### ISSUE TITLE
Error: npm publish - Too many dependencies

### ISSUE THREAD

**Issue by dragonnomada** [Hermanya/create-react-hook#50]
I can't upload and publish my hook :(

---

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\<my-pc-user>\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'publish',
0 verbose cli   '--access=public'
0 verbose cli ]
1 info using npm@7.5.4
2 info using node@v14.15.5
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Users\<my-pc-user>\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 3ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:E:\santuario\hooks\use-window-size\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\<my-pc-user>\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Users\<my-pc-user>\AppData\Roaming\npm\etc\npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 13ms
19 verbose npm-session a28a22955a7dfe8e
20 timing npm:load Completed in 29ms
21 verbose publish [ '.' ]
22 notice
23 notice 📦  <my-npm-user>/use-window-size@1.0.0
24 notice === Tarball Contents ===
25 notice 2.0kB   README.md
25 notice 165B    .babelrc
25 notice 147B    .editorconfig
25 notice 26B     .env
25 notice 416B    .eslintrc
25 notice 68B     .travis.yml
25 notice 4.0kB   dist/index.es.js
25 notice 3.9kB   dist/index.es.js.map
25 notice 4.1kB   dist/index.js
25 notice 3.9kB   dist/index.js.map
25 notice 239B    example/.env
25 notice 1.2MB   example/package-lock.json
25 notice 658B    example/package.json
25 notice 466B    example/public/index.html
25 notice 210B    example/public/manifest.json
25 notice 104.9kB example/README.md
25 notice 1.4kB   example/src/App.js
25 notice 162B    example/src/index.css
25 notice 164B    example/src/index.js
25 notice 34.2kB  package.json
25 notice 631B    rollup.config.js
25 notice 36B     src/.eslintrc
25 notice 1.6kB   src/index.js
25 notice 628B    src/index.test.js
26 notice === Tarball Details ===
27 notice name:          <my-npm-user>/use-window-size
27 notice version:       1.0.0
27 notice filename:      <my-npm-user>/use-window-size-1.0.0.tgz
27 notice package size:  351.4 kB
27 notice unpacked size: 1.4 MB
27 notice shasum:        634ace7dec98367e1007eac6bf92800e93befc46
27 notice integrity:     sha512-s6wfGxdiIQuXr[...]Sbwo4xU5Dyz0Q==
27 notice total files:   24
28 notice
29 http fetch PUT 400 https://registry.npmjs.org/<my-npm-user>%2fuse-window-size 3546ms
30 timing command:publish Completed in 8340ms
31 verbose stack Error: 400 Bad Request - PUT https://registry.npmjs.org/<my-npm-user>%2fuse-window-size - Too many dependencies.
31 verbose stack     at C:\Users\<my-pc-user>\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:123:15
31 verbose stack     at async publish (C:\Users\<my-pc-user>\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmpublish\publish.js:43:12)
31 verbose stack     at async publish_ (C:\Users\<my-pc-user>\AppData\Roaming\npm\node_modules\npm\lib\publish.js:115:5)
31 verbose stack     at async publish (C:\Users\<my-pc-user>\AppData\Roaming\npm\node_modules\npm\lib\publish.js:44:19)
32 verbose statusCode 400
33 verbose pkgid <my-npm-user>/use-window-size@1.0.0
34 verbose cwd E:\santuario\hooks\use-window-size
35 verbose Windows_NT 10.0.19041
36 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\<my-pc-user>\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "publish" "--access=public"
37 verbose node v14.15.5
38 verbose npm  v7.5.4
39 error code E400
40 error 400 Bad Request - PUT https://registry.npmjs.org/<my-npm-user>%2fuse-window-size - Too many dependencies.
41 verbose exit 1

**Comment by ShaharEli** [comment]
You need to add to .npmignore file in the root of the project and add this inside:
example
src
.env
.travis.yml
node_modules
dist/index.es.js    
dist/index.es.js.map    
dist/index.js.map    
dist/index.d.ts    
tsconfig.json 
tsconfig.test.json
rollup.config.js
README.md
